configType = "standard-overrides"
l1ChainID = 11155111
opcmAddress = "0x44c191ce5ce35131e703532af75fa9ca221e2398"
fundDevAccounts = false
l1ContractsLocator = "file://__ROOT__/packages/contracts-bedrock/forge-artifacts"
l2ContractsLocator = "file://__ROOT__/packages/contracts-bedrock/forge-artifacts"

[[chains]]
  id = "0x0000000000000000000000000000000000000000000000000000000000000385"

  baseFeeVaultRecipient = "0xBATCHER"
  l1FeeVaultRecipient = "0xBATCHER"
  sequencerFeeVaultRecipient = "0xBATCHER"

  eip1559DenominatorCanyon = 250
  eip1559Denominator = 50
  eip1559Elasticity = 6
  operatorFeeScalar = 0
  operatorFeeConstant = 0
  [chains.roles]
    l1ProxyAdminOwner = "0xBATCHER"
    l2ProxyAdminOwner = "0x2fc3ffc903729a0f03966b917003800b145f67f3"
    systemConfigOwner = "0xBATCHER"
    unsafeBlockSigner = "0xBATCHER"
    batcher = "0xBATCHER"
    challenger = "0xfd1d2e729ae8eee2e146c033bf4400fe75284301"


