package main

import (
	"encoding/json"
	"fmt"
	"os"
	"time"

	"github.com/ethereum-optimism/optimism/op-node/flow"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: analyzer <trace-file.json> [options]")
		fmt.Println("       analyzer --help")
		os.Exit(1)
	}

	arg := os.Args[1]
	if arg == "--help" || arg == "-h" {
		printHelp()
		return
	}

	filename := arg
	if err := analyzeTrace(filename); err != nil {
		fmt.Printf("Error analyzing trace: %v\n", err)
		os.Exit(1)
	}
}

func printHelp() {
	fmt.Println("Flow Trace Analyzer")
	fmt.Println("")
	fmt.Println("Analyzes JSON trace files generated by the op-node flow tracer.")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  analyzer <trace-file.json>   Analyze a single trace file")
	fmt.Println("  analyzer --help              Show this help message")
	fmt.Println("")
	fmt.Println("Example:")
	fmt.Println("  analyzer /tmp/flow-traces/flow-events-20240731-143022.json")
	fmt.Println("")
	fmt.Println("The analyzer provides:")
	fmt.Println("  • Event summary statistics")
	fmt.Println("  • Flow completeness metrics")
	fmt.Println("  • Performance analysis")
	fmt.Println("  • Event pattern identification")
	fmt.Println("  • Correlation analysis")
}

func analyzeTrace(filename string) error {
	fmt.Printf("🔍 Analyzing trace file: %s\n", filename)
	fmt.Println()

	// Read the trace file
	data, err := os.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}

	var trace flow.FlowTraceOutput
	if err := json.Unmarshal(data, &trace); err != nil {
		return fmt.Errorf("failed to parse JSON: %w", err)
	}

	// Print comprehensive analysis
	printMetadataAnalysis(trace.Metadata)
	printEventAnalysis(trace.Events)
	printCorrelationAnalysis(trace.Correlations, trace.Events)
	printPerformanceAnalysis(trace.Events, trace.Metadata)
	printPatternAnalysis(trace.Events)
	printCompletenessAnalysis(trace)

	return nil
}

func printMetadataAnalysis(metadata flow.TraceMetadata) {
	fmt.Println("📊 TRACE METADATA")
	fmt.Printf("   Duration: %v\n", metadata.TotalDuration)
	fmt.Printf("   Events Captured: %d\n", metadata.TotalEvents)
	fmt.Printf("   Start Time: %s\n", metadata.StartTime.Format(time.RFC3339))
	fmt.Printf("   End Time: %s\n", metadata.EndTime.Format(time.RFC3339))
	fmt.Printf("   Version: %s\n", metadata.Version)
	fmt.Println()
}

func printEventAnalysis(events []flow.CapturedEvent) {
	fmt.Println("📈 EVENT ANALYSIS")

	if len(events) == 0 {
		fmt.Println("   No events captured")
		return
	}

	// Count events by name
	eventCounts := make(map[string]int)
	var totalDuration time.Duration
	effectiveEvents := 0

	for _, event := range events {
		eventCounts[event.EventName]++
		totalDuration += event.Duration
		if event.Effect {
			effectiveEvents++
		}
	}

	fmt.Printf("   Total Events: %d\n", len(events))
	fmt.Printf("   Effective Events: %d (%.1f%%)\n", effectiveEvents, float64(effectiveEvents)/float64(len(events))*100)
	fmt.Printf("   Average Duration: %v\n", totalDuration/time.Duration(len(events)))
	fmt.Println()

	// Top events by frequency
	fmt.Println("   🔥 Most Frequent Events:")
	printTopEvents(eventCounts, 5)
	fmt.Println()
}

func printCorrelationAnalysis(correlations map[uint64]uint64, events []flow.CapturedEvent) {
	fmt.Println("🔗 CORRELATION ANALYSIS")
	fmt.Printf("   Total Correlations: %d\n", len(correlations))

	if len(events) > 0 {
		correlationRate := float64(len(correlations)) / float64(len(events)) * 100
		fmt.Printf("   Correlation Rate: %.1f%%\n", correlationRate)

		if correlationRate > 80 {
			fmt.Println("   Status: ✅ Excellent correlation coverage")
		} else if correlationRate > 60 {
			fmt.Println("   Status: ✅ Good correlation coverage")
		} else if correlationRate > 40 {
			fmt.Println("   Status: ⚠️  Moderate correlation coverage")
		} else {
			fmt.Println("   Status: ❌ Low correlation coverage")
		}
	}
	fmt.Println()
}

func printPerformanceAnalysis(events []flow.CapturedEvent, metadata flow.TraceMetadata) {
	fmt.Println("⚡ PERFORMANCE ANALYSIS")

	if len(events) == 0 {
		fmt.Println("   No events to analyze")
		return
	}

	// Calculate throughput
	throughput := float64(len(events)) / metadata.TotalDuration.Seconds()
	fmt.Printf("   Throughput: %.2f events/second\n", throughput)

	// Find slowest events
	slowestEvents := findSlowestEvents(events, 3)
	if len(slowestEvents) > 0 {
		fmt.Println("   🐌 Slowest Events:")
		for i, event := range slowestEvents {
			fmt.Printf("      %d. %s: %v\n", i+1, event.EventName, event.Duration)
		}
	}

	// Event processing efficiency
	var processedEvents int
	for _, event := range events {
		if event.Duration > 0 {
			processedEvents++
		}
	}

	efficiency := float64(processedEvents) / float64(len(events)) * 100
	fmt.Printf("   Processing Efficiency: %.1f%%\n", efficiency)
	fmt.Println()
}

func printPatternAnalysis(events []flow.CapturedEvent) {
	fmt.Println("🔍 PATTERN ANALYSIS")

	if len(events) < 2 {
		fmt.Println("   Insufficient events for pattern analysis")
		fmt.Println()
		return
	}

	// Simple sequential pattern detection
	patterns := make(map[string]int)
	for i := 0; i < len(events)-1; i++ {
		pattern := events[i].EventName + " → " + events[i+1].EventName
		patterns[pattern]++
	}

	fmt.Printf("   Unique Patterns Found: %d\n", len(patterns))

	if len(patterns) > 0 {
		fmt.Println("   🔄 Most Common Sequences:")
		printTopPatterns(patterns, 3)
	}
	fmt.Println()
}

func printCompletenessAnalysis(trace flow.FlowTraceOutput) {
	fmt.Println("✅ COMPLETENESS ANALYSIS")

	// Basic completeness heuristics
	score := 0
	maxScore := 5

	// Check 1: Events captured
	if len(trace.Events) > 0 {
		score++
		fmt.Println("   ✅ Events captured")
	} else {
		fmt.Println("   ❌ No events captured")
	}

	// Check 2: Correlations present
	if len(trace.Correlations) > 0 {
		score++
		fmt.Println("   ✅ Event correlations tracked")
	} else {
		fmt.Println("   ⚠️  No event correlations found")
	}

	// Check 3: Duration reasonable
	if trace.Metadata.TotalDuration > time.Second {
		score++
		fmt.Println("   ✅ Reasonable trace duration")
	} else {
		fmt.Println("   ⚠️  Very short trace duration")
	}

	// Check 4: Effective events
	effectiveCount := 0
	for _, event := range trace.Events {
		if event.Effect {
			effectiveCount++
		}
	}
	if effectiveCount > 0 {
		score++
		fmt.Println("   ✅ Effective events detected")
	} else {
		fmt.Println("   ⚠️  No effective events found")
	}

	// Check 5: Multiple event types
	eventTypes := make(map[string]bool)
	for _, event := range trace.Events {
		eventTypes[event.EventName] = true
	}
	if len(eventTypes) >= 3 {
		score++
		fmt.Println("   ✅ Multiple event types captured")
	} else {
		fmt.Println("   ⚠️  Limited event type diversity")
	}

	completeness := float64(score) / float64(maxScore) * 100
	fmt.Printf("   Overall Completeness: %.0f%% (%d/%d)\n", completeness, score, maxScore)

	if completeness >= 80 {
		fmt.Println("   🎉 Excellent trace quality!")
	} else if completeness >= 60 {
		fmt.Println("   👍 Good trace quality")
	} else {
		fmt.Println("   ⚠️  Trace quality could be improved")
	}
	fmt.Println()
}

// Helper functions

func printTopEvents(eventCounts map[string]int, limit int) {
	type eventCount struct {
		name  string
		count int
	}

	var events []eventCount
	for name, count := range eventCounts {
		events = append(events, eventCount{name, count})
	}

	// Simple bubble sort by count (descending)
	for i := 0; i < len(events); i++ {
		for j := i + 1; j < len(events); j++ {
			if events[i].count < events[j].count {
				events[i], events[j] = events[j], events[i]
			}
		}
	}

	for i, event := range events {
		if i >= limit {
			break
		}
		fmt.Printf("      %d. %s: %d occurrences\n", i+1, event.name, event.count)
	}
}

func printTopPatterns(patterns map[string]int, limit int) {
	type pattern struct {
		sequence string
		count    int
	}

	var patternList []pattern
	for seq, count := range patterns {
		if count > 1 { // Only show patterns that occur more than once
			patternList = append(patternList, pattern{seq, count})
		}
	}

	// Simple bubble sort by count (descending)
	for i := 0; i < len(patternList); i++ {
		for j := i + 1; j < len(patternList); j++ {
			if patternList[i].count < patternList[j].count {
				patternList[i], patternList[j] = patternList[j], patternList[i]
			}
		}
	}

	for i, p := range patternList {
		if i >= limit {
			break
		}
		fmt.Printf("      %d. %s (%d times)\n", i+1, p.sequence, p.count)
	}
}

func findSlowestEvents(events []flow.CapturedEvent, limit int) []flow.CapturedEvent {
	// Create a copy to avoid modifying original
	eventsCopy := make([]flow.CapturedEvent, len(events))
	copy(eventsCopy, events)

	// Simple bubble sort by duration (descending)
	for i := 0; i < len(eventsCopy); i++ {
		for j := i + 1; j < len(eventsCopy); j++ {
			if eventsCopy[i].Duration < eventsCopy[j].Duration {
				eventsCopy[i], eventsCopy[j] = eventsCopy[j], eventsCopy[i]
			}
		}
	}

	if len(eventsCopy) > limit {
		return eventsCopy[:limit]
	}
	return eventsCopy
}
