package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/ethereum-optimism/optimism/op-node/flow"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: analyzer <trace-file.json> [options]")
		fmt.Println("       analyzer --help")
		os.Exit(1)
	}

	arg := os.Args[1]
	if arg == "--help" || arg == "-h" {
		printHelp()
		return
	}

	filename := arg
	if err := analyzeTrace(filename); err != nil {
		fmt.Printf("Error analyzing trace: %v\n", err)
		os.Exit(1)
	}
}

func printHelp() {
	fmt.Println("Flow Trace Analyzer")
	fmt.Println("")
	fmt.Println("Analyzes JSON trace files generated by the op-node flow tracer.")
	fmt.Println("")
	fmt.Println("Usage:")
	fmt.Println("  analyzer <trace-file.json>   Analyze a single trace file")
	fmt.Println("  analyzer --help              Show this help message")
	fmt.Println("")
	fmt.Println("Example:")
	fmt.Println("  analyzer /tmp/flow-traces/flow-events-20240731-143022.json")
	fmt.Println("")
	fmt.Println("The analyzer provides:")
	fmt.Println("  • Event summary statistics")
	fmt.Println("  • Flow completeness metrics")
	fmt.Println("  • Performance analysis")
	fmt.Println("  • Event pattern identification")
	fmt.Println("  • Correlation analysis")
}

func analyzeTrace(filename string) error {
	fmt.Printf("🔍 Analyzing trace file: %s\n", filename)
	fmt.Println()

	// Read the trace file
	data, err := os.ReadFile(filename)
	if err != nil {
		return fmt.Errorf("failed to read file: %w", err)
	}

	var trace flow.FlowTraceOutput
	if err := json.Unmarshal(data, &trace); err != nil {
		return fmt.Errorf("failed to parse JSON: %w", err)
	}

	// Print comprehensive analysis
	printMetadataAnalysis(trace.Metadata)
	printEventAnalysis(trace.Events)
	printCorrelationAnalysis(trace.Correlations, trace.Events)
	printPerformanceAnalysis(trace.Events, trace.Metadata)
	printPatternAnalysis(trace.Events)

	// 🚀 AST Generation and Graph Export
	builder := flow.NewFlowBuilder(trace.Events, trace.Correlations)
	flowGraph, err := builder.BuildAST()
	if err != nil {
		fmt.Printf("Error building AST: %v\n", err)
	} else {
		printASTAnalysis(flowGraph)
		generateGraphOutputs(flowGraph, filename)
	}

	// 🎯 NEW: Generate causal event chain analysis
	printCallTraceAnalysis(trace.Events)

	printCompletenessAnalysis(trace)

	return nil
}

func printMetadataAnalysis(metadata flow.TraceMetadata) {
	fmt.Println("📊 TRACE METADATA")
	fmt.Printf("   Duration: %v\n", metadata.TotalDuration)
	fmt.Printf("   Events Captured: %d\n", metadata.TotalEvents)
	fmt.Printf("   Start Time: %s\n", metadata.StartTime.Format(time.RFC3339))
	fmt.Printf("   End Time: %s\n", metadata.EndTime.Format(time.RFC3339))
	fmt.Printf("   Version: %s\n", metadata.Version)
	fmt.Println()
}

func printEventAnalysis(events []flow.CapturedEvent) {
	fmt.Println("📈 EVENT ANALYSIS")

	if len(events) == 0 {
		fmt.Println("   No events captured")
		return
	}

	// Count events by name
	eventCounts := make(map[string]int)
	var totalDuration time.Duration
	effectiveEvents := 0

	for _, event := range events {
		eventCounts[event.EventName]++
		totalDuration += event.Duration
		if event.Effect {
			effectiveEvents++
		}
	}

	fmt.Printf("   Total Events: %d\n", len(events))
	fmt.Printf("   Effective Events: %d (%.1f%%)\n", effectiveEvents, float64(effectiveEvents)/float64(len(events))*100)
	fmt.Printf("   Average Duration: %v\n", totalDuration/time.Duration(len(events)))
	fmt.Println()

	// Top events by frequency
	fmt.Println("   🔥 Most Frequent Events:")
	printTopEvents(eventCounts, 5)
	fmt.Println()
}

func printCorrelationAnalysis(correlations map[uint64]uint64, events []flow.CapturedEvent) {
	fmt.Println("🔗 CORRELATION ANALYSIS")
	fmt.Printf("   Total Correlations: %d\n", len(correlations))

	if len(events) > 0 {
		correlationRate := float64(len(correlations)) / float64(len(events)) * 100
		fmt.Printf("   Correlation Rate: %.1f%%\n", correlationRate)

		if correlationRate > 80 {
			fmt.Println("   Status: ✅ Excellent correlation coverage")
		} else if correlationRate > 60 {
			fmt.Println("   Status: ✅ Good correlation coverage")
		} else if correlationRate > 40 {
			fmt.Println("   Status: ⚠️  Moderate correlation coverage")
		} else {
			fmt.Println("   Status: ❌ Low correlation coverage")
		}
	}
	fmt.Println()
}

func printPerformanceAnalysis(events []flow.CapturedEvent, metadata flow.TraceMetadata) {
	fmt.Println("⚡ PERFORMANCE ANALYSIS")

	if len(events) == 0 {
		fmt.Println("   No events to analyze")
		return
	}

	// Calculate throughput
	throughput := float64(len(events)) / metadata.TotalDuration.Seconds()
	fmt.Printf("   Throughput: %.2f events/second\n", throughput)

	// Find slowest events
	slowestEvents := findSlowestEvents(events, 3)
	if len(slowestEvents) > 0 {
		fmt.Println("   🐌 Slowest Events:")
		for i, event := range slowestEvents {
			fmt.Printf("      %d. %s: %v\n", i+1, event.EventName, event.Duration)
		}
	}

	// Event processing efficiency
	var processedEvents int
	for _, event := range events {
		if event.Duration > 0 {
			processedEvents++
		}
	}

	efficiency := float64(processedEvents) / float64(len(events)) * 100
	fmt.Printf("   Processing Efficiency: %.1f%%\n", efficiency)
	fmt.Println()
}

func printPatternAnalysis(events []flow.CapturedEvent) {
	fmt.Println("🔍 PATTERN ANALYSIS")

	if len(events) < 2 {
		fmt.Println("   Insufficient events for pattern analysis")
		fmt.Println()
		return
	}

	// Simple sequential pattern detection
	patterns := make(map[string]int)
	for i := 0; i < len(events)-1; i++ {
		pattern := events[i].EventName + " → " + events[i+1].EventName
		patterns[pattern]++
	}

	fmt.Printf("   Unique Patterns Found: %d\n", len(patterns))

	if len(patterns) > 0 {
		fmt.Println("   🔄 Most Common Sequences:")
		printTopPatterns(patterns, 3)
	}
	fmt.Println()
}

func printCompletenessAnalysis(trace flow.FlowTraceOutput) {
	fmt.Println("✅ COMPLETENESS ANALYSIS")

	// Basic completeness heuristics
	score := 0
	maxScore := 5

	// Check 1: Events captured
	if len(trace.Events) > 0 {
		score++
		fmt.Println("   ✅ Events captured")
	} else {
		fmt.Println("   ❌ No events captured")
	}

	// Check 2: Correlations present
	if len(trace.Correlations) > 0 {
		score++
		fmt.Println("   ✅ Event correlations tracked")
	} else {
		fmt.Println("   ⚠️  No event correlations found")
	}

	// Check 3: Duration reasonable
	if trace.Metadata.TotalDuration > time.Second {
		score++
		fmt.Println("   ✅ Reasonable trace duration")
	} else {
		fmt.Println("   ⚠️  Very short trace duration")
	}

	// Check 4: Effective events
	effectiveCount := 0
	for _, event := range trace.Events {
		if event.Effect {
			effectiveCount++
		}
	}
	if effectiveCount > 0 {
		score++
		fmt.Println("   ✅ Effective events detected")
	} else {
		fmt.Println("   ⚠️  No effective events found")
	}

	// Check 5: Multiple event types
	eventTypes := make(map[string]bool)
	for _, event := range trace.Events {
		eventTypes[event.EventName] = true
	}
	if len(eventTypes) >= 3 {
		score++
		fmt.Println("   ✅ Multiple event types captured")
	} else {
		fmt.Println("   ⚠️  Limited event type diversity")
	}

	completeness := float64(score) / float64(maxScore) * 100
	fmt.Printf("   Overall Completeness: %.0f%% (%d/%d)\n", completeness, score, maxScore)

	if completeness >= 80 {
		fmt.Println("   🎉 Excellent trace quality!")
	} else if completeness >= 60 {
		fmt.Println("   👍 Good trace quality")
	} else {
		fmt.Println("   ⚠️  Trace quality could be improved")
	}
	fmt.Println()
}

// Helper functions

func printTopEvents(eventCounts map[string]int, limit int) {
	type eventCount struct {
		name  string
		count int
	}

	var events []eventCount
	for name, count := range eventCounts {
		events = append(events, eventCount{name, count})
	}

	// Simple bubble sort by count (descending)
	for i := 0; i < len(events); i++ {
		for j := i + 1; j < len(events); j++ {
			if events[i].count < events[j].count {
				events[i], events[j] = events[j], events[i]
			}
		}
	}

	for i, event := range events {
		if i >= limit {
			break
		}
		fmt.Printf("      %d. %s: %d occurrences\n", i+1, event.name, event.count)
	}
}

func printTopPatterns(patterns map[string]int, limit int) {
	type pattern struct {
		sequence string
		count    int
	}

	var patternList []pattern
	for seq, count := range patterns {
		if count > 1 { // Only show patterns that occur more than once
			patternList = append(patternList, pattern{seq, count})
		}
	}

	// Simple bubble sort by count (descending)
	for i := 0; i < len(patternList); i++ {
		for j := i + 1; j < len(patternList); j++ {
			if patternList[i].count < patternList[j].count {
				patternList[i], patternList[j] = patternList[j], patternList[i]
			}
		}
	}

	for i, p := range patternList {
		if i >= limit {
			break
		}
		fmt.Printf("      %d. %s (%d times)\n", i+1, p.sequence, p.count)
	}
}

func findSlowestEvents(events []flow.CapturedEvent, limit int) []flow.CapturedEvent {
	// Create a copy to avoid modifying original
	eventsCopy := make([]flow.CapturedEvent, len(events))
	copy(eventsCopy, events)

	// Simple bubble sort by duration (descending)
	for i := 0; i < len(eventsCopy); i++ {
		for j := i + 1; j < len(eventsCopy); j++ {
			if eventsCopy[i].Duration < eventsCopy[j].Duration {
				eventsCopy[i], eventsCopy[j] = eventsCopy[j], eventsCopy[i]
			}
		}
	}

	if len(eventsCopy) > limit {
		return eventsCopy[:limit]
	}
	return eventsCopy
}

// 🚀 NEW: AST Analysis function
func printASTAnalysis(flowGraph *flow.FlowGraph) {
	fmt.Println("🏗️ AST GENERATION & FLOW ANALYSIS")

	fmt.Println("   ✅ AST Generation Successful!")
	fmt.Printf("   Flow Graph ID: %s\n", flowGraph.ID)
	fmt.Printf("   Flow Name: %s\n", flowGraph.Name)
	fmt.Printf("   Total Nodes: %d\n", len(flowGraph.Nodes))
	fmt.Printf("   Total Edges: %d\n", len(flowGraph.Edges))
	fmt.Printf("   Entry Points: %v\n", flowGraph.EntryPoints)
	fmt.Println()

	// Analysis of generated flow graph
	fmt.Println("   📊 Flow Graph Statistics:")
	fmt.Printf("      Observed Execution Paths: %d\n", len(flowGraph.ObservedPaths))

	if flowGraph.Metrics != nil {
		fmt.Printf("      Execution Count: %d\n", flowGraph.Metrics.ExecutionCount)
		fmt.Printf("      Success Rate: %.1f%%\n", flowGraph.Metrics.SuccessRate*100)
		fmt.Printf("      Average Duration: %v\n", flowGraph.Metrics.AverageDuration)
		if len(flowGraph.Metrics.BottleneckNodes) > 0 {
			fmt.Printf("      Bottleneck Nodes: %v\n", flowGraph.Metrics.BottleneckNodes)
		}
	}

	// Node type analysis
	nodeTypes := make(map[string]int)
	for _, node := range flowGraph.Nodes {
		nodeTypes[node.Type().String()]++
	}

	fmt.Println("   🎯 Node Type Distribution:")
	for nodeType, count := range nodeTypes {
		fmt.Printf("      %s: %d nodes\n", nodeType, count)
	}

	// Edge analysis
	if len(flowGraph.Edges) > 0 {
		totalWeight := 0.0
		for _, edge := range flowGraph.Edges {
			totalWeight += edge.Weight
		}
		avgWeight := totalWeight / float64(len(flowGraph.Edges))

		fmt.Println("   🔗 Edge Statistics:")
		fmt.Printf("      Average Transition Weight: %.2f\n", avgWeight)
		fmt.Printf("      Most Common Transitions:\n")

		// Sort edges by weight to show most common transitions
		sortedEdges := make([]flow.FlowEdge, len(flowGraph.Edges))
		copy(sortedEdges, flowGraph.Edges)
		sort.Slice(sortedEdges, func(i, j int) bool {
			return sortedEdges[i].Weight > sortedEdges[j].Weight
		})

		for i, edge := range sortedEdges {
			if i >= 5 { // Top 5
				break
			}
			fmt.Printf("         %s → %s (weight: %.0f)\n", edge.From, edge.To, edge.Weight)
		}
	}

	fmt.Println()
}

// 🎨 Graph Generation Functions

func generateGraphOutputs(flowGraph *flow.FlowGraph, traceFilename string) {
	fmt.Println("🎨 GENERATING FLOW VISUALIZATIONS")

	// Generate base filename from trace file
	baseFilename := strings.TrimSuffix(traceFilename, ".json")

	// Generate GraphViz .dot file
	dotFile := baseFilename + "_flow.dot"
	if err := generateGraphViz(flowGraph, dotFile); err != nil {
		fmt.Printf("   ❌ Error generating GraphViz: %v\n", err)
	} else {
		fmt.Printf("   ✅ GraphViz saved: %s\n", dotFile)
		fmt.Printf("      To render: dot -Tpng %s -o %s.png\n", dotFile, baseFilename)
	}

	// Generate Mermaid .mmd file
	mermaidFile := baseFilename + "_flow.mmd"
	if err := generateMermaid(flowGraph, mermaidFile); err != nil {
		fmt.Printf("   ❌ Error generating Mermaid: %v\n", err)
	} else {
		fmt.Printf("   ✅ Mermaid saved: %s\n", mermaidFile)
		fmt.Printf("      View at: https://mermaid.live/ or use mermaid-cli\n")
	}

	// Generate summary report
	reportFile := baseFilename + "_analysis.md"
	if err := generateAnalysisReport(flowGraph, reportFile); err != nil {
		fmt.Printf("   ❌ Error generating report: %v\n", err)
	} else {
		fmt.Printf("   ✅ Analysis report: %s\n", reportFile)
	}

	fmt.Println()
}

func generateGraphViz(flowGraph *flow.FlowGraph, filename string) error {
	var dot strings.Builder

	dot.WriteString("digraph FlowGraph {\n")
	dot.WriteString("  rankdir=TB;\n")
	dot.WriteString("  node [shape=box, style=\"rounded,filled\", fontname=\"Arial\"];\n")
	dot.WriteString("  edge [fontname=\"Arial\", fontsize=10];\n\n")

	// Add title
	dot.WriteString(fmt.Sprintf("  label=\"%s\\nNodes: %d, Edges: %d\";\n",
		flowGraph.Name, len(flowGraph.Nodes), len(flowGraph.Edges)))
	dot.WriteString("  labelloc=t;\n")
	dot.WriteString("  fontsize=16;\n\n")

	// Add nodes with colors based on type
	for nodeID, node := range flowGraph.Nodes {
		color := getNodeColor(node.Type())
		safeID := strings.ReplaceAll(nodeID, "-", "_")
		label := strings.ReplaceAll(nodeID, "-", "\\n")

		dot.WriteString(fmt.Sprintf("  %s [label=\"%s\", fillcolor=\"%s\"];\n",
			safeID, label, color))
	}

	dot.WriteString("\n")

	// Add edges with weights
	for _, edge := range flowGraph.Edges {
		fromSafe := strings.ReplaceAll(edge.From, "-", "_")
		toSafe := strings.ReplaceAll(edge.To, "-", "_")

		// Thicker lines for more frequent transitions
		penwidth := 1.0 + (edge.Weight / 10.0)
		if penwidth > 5.0 {
			penwidth = 5.0
		}

		dot.WriteString(fmt.Sprintf("  %s -> %s [label=\"%.0f\", penwidth=%.1f];\n",
			fromSafe, toSafe, edge.Weight, penwidth))
	}

	dot.WriteString("}\n")

	return os.WriteFile(filename, []byte(dot.String()), 0644)
}

func generateMermaid(flowGraph *flow.FlowGraph, filename string) error {
	var mmd strings.Builder

	mmd.WriteString("graph TD\n")
	mmd.WriteString(fmt.Sprintf("  %% %s - Nodes: %d, Edges: %d\n\n",
		flowGraph.Name, len(flowGraph.Nodes), len(flowGraph.Edges)))

	// Add nodes with shapes based on type
	for nodeID, node := range flowGraph.Nodes {
		shape := getMermaidShape(node.Type())
		safeID := strings.ReplaceAll(nodeID, "-", "_")
		label := strings.ReplaceAll(nodeID, "-", " ")

		mmd.WriteString(fmt.Sprintf("  %s%s\"%s\"%s\n", safeID, shape[0], label, shape[1]))
	}

	mmd.WriteString("\n")

	// Add edges
	for _, edge := range flowGraph.Edges {
		fromSafe := strings.ReplaceAll(edge.From, "-", "_")
		toSafe := strings.ReplaceAll(edge.To, "-", "_")

		// Thicker arrows for more frequent transitions
		arrow := "-->"
		if edge.Weight > 5 {
			arrow = "==>"
		}

		mmd.WriteString(fmt.Sprintf("  %s %s|%.0f| %s\n",
			fromSafe, arrow, edge.Weight, toSafe))
	}

	// Add styling
	mmd.WriteString("\n  %% Styling\n")
	for nodeID, node := range flowGraph.Nodes {
		safeID := strings.ReplaceAll(nodeID, "-", "_")
		class := getMermaidClass(node.Type())
		mmd.WriteString(fmt.Sprintf("  class %s %s\n", safeID, class))
	}

	mmd.WriteString("\n  classDef trigger fill:#e1f5fe\n")
	mmd.WriteString("  classDef action fill:#f3e5f5\n")
	mmd.WriteString("  classDef decision fill:#fff3e0\n")
	mmd.WriteString("  classDef sync fill:#e8f5e8\n")
	mmd.WriteString("  classDef terminal fill:#ffebee\n")

	return os.WriteFile(filename, []byte(mmd.String()), 0644)
}

func generateAnalysisReport(flowGraph *flow.FlowGraph, filename string) error {
	var report strings.Builder

	report.WriteString(fmt.Sprintf("# Flow Analysis Report: %s\n\n", flowGraph.Name))
	report.WriteString(fmt.Sprintf("Generated: %s\n\n", time.Now().Format("2006-01-02 15:04:05")))

	// Summary
	report.WriteString("## Summary\n\n")
	report.WriteString(fmt.Sprintf("- **Total Nodes**: %d\n", len(flowGraph.Nodes)))
	report.WriteString(fmt.Sprintf("- **Total Edges**: %d\n", len(flowGraph.Edges)))
	report.WriteString(fmt.Sprintf("- **Entry Points**: %v\n", flowGraph.EntryPoints))
	report.WriteString(fmt.Sprintf("- **Execution Paths**: %d\n\n", len(flowGraph.ObservedPaths)))

	// Node analysis
	nodeTypes := make(map[string]int)
	for _, node := range flowGraph.Nodes {
		nodeTypes[node.Type().String()]++
	}

	report.WriteString("## Node Type Distribution\n\n")
	for nodeType, count := range nodeTypes {
		report.WriteString(fmt.Sprintf("- **%s**: %d nodes\n", nodeType, count))
	}
	report.WriteString("\n")

	// Top transitions
	if len(flowGraph.Edges) > 0 {
		// Sort edges by weight
		sortedEdges := make([]flow.FlowEdge, len(flowGraph.Edges))
		copy(sortedEdges, flowGraph.Edges)
		sort.Slice(sortedEdges, func(i, j int) bool {
			return sortedEdges[i].Weight > sortedEdges[j].Weight
		})

		report.WriteString("## Most Common Transitions\n\n")
		for i, edge := range sortedEdges {
			if i >= 10 { // Top 10
				break
			}
			report.WriteString(fmt.Sprintf("%d. **%s → %s** (weight: %.0f)\n",
				i+1, edge.From, edge.To, edge.Weight))
		}
		report.WriteString("\n")
	}

	// Performance insights
	if flowGraph.Metrics != nil {
		report.WriteString("## Performance Insights\n\n")
		report.WriteString(fmt.Sprintf("- **Success Rate**: %.1f%%\n", flowGraph.Metrics.SuccessRate*100))
		report.WriteString(fmt.Sprintf("- **Average Duration**: %v\n", flowGraph.Metrics.AverageDuration))
		if len(flowGraph.Metrics.BottleneckNodes) > 0 {
			report.WriteString(fmt.Sprintf("- **Bottleneck Nodes**: %v\n", flowGraph.Metrics.BottleneckNodes))
		}
		report.WriteString("\n")
	}

	// Refactoring recommendations
	report.WriteString("## Refactoring Recommendations\n\n")
	report.WriteString("Based on the flow analysis:\n\n")

	// Find nodes with high fan-out (decision points)
	fanOut := make(map[string]int)
	for _, edge := range flowGraph.Edges {
		fanOut[edge.From]++
	}

	for nodeID, count := range fanOut {
		if count >= 3 {
			report.WriteString(fmt.Sprintf("- **%s** has %d outgoing transitions - consider explicit state machine\n", nodeID, count))
		}
	}

	// Find bottlenecks
	if flowGraph.Metrics != nil && len(flowGraph.Metrics.BottleneckNodes) > 0 {
		report.WriteString("- Consider optimizing bottleneck nodes:\n")
		for _, node := range flowGraph.Metrics.BottleneckNodes {
			report.WriteString(fmt.Sprintf("  - %s\n", node))
		}
	}

	return os.WriteFile(filename, []byte(report.String()), 0644)
}

// Helper functions for styling

func getNodeColor(nodeType flow.FlowNodeType) string {
	switch nodeType {
	case flow.EventTrigger:
		return "lightblue"
	case flow.StateCheck:
		return "lightgreen"
	case flow.ActionNode:
		return "lightyellow"
	case flow.DecisionNode:
		return "orange"
	case flow.SyncPoint:
		return "lightgray"
	case flow.TerminalNode:
		return "lightcoral"
	default:
		return "white"
	}
}

func getMermaidShape(nodeType flow.FlowNodeType) [2]string {
	switch nodeType {
	case flow.EventTrigger:
		return [2]string{"(", ")"} // Round
	case flow.StateCheck:
		return [2]string{"{", "}"} // Diamond
	case flow.ActionNode:
		return [2]string{"[", "]"} // Rectangle
	case flow.DecisionNode:
		return [2]string{"{", "}"} // Diamond
	case flow.SyncPoint:
		return [2]string{"[[", "]]"} // Subroutine
	case flow.TerminalNode:
		return [2]string{"((", "))"} // Circle
	default:
		return [2]string{"[", "]"} // Rectangle
	}
}

func getMermaidClass(nodeType flow.FlowNodeType) string {
	switch nodeType {
	case flow.EventTrigger:
		return "trigger"
	case flow.StateCheck:
		return "action"
	case flow.ActionNode:
		return "action"
	case flow.DecisionNode:
		return "decision"
	case flow.SyncPoint:
		return "sync"
	case flow.TerminalNode:
		return "terminal"
	default:
		return "action"
	}
}

// 🎯 NEW: Print causal event chain analysis
func printCallTraceAnalysis(events []flow.CapturedEvent) {
	fmt.Println("🎯 CAUSAL EVENT CHAIN ANALYSIS")

	// Find root events (events with no parent)
	rootEvents := make([]flow.CapturedEvent, 0)
	eventsByDepth := make(map[int][]flow.CapturedEvent)
	maxDepth := 0

	for _, event := range events {
		if event.ParentEventID == 0 {
			rootEvents = append(rootEvents, event)
		}

		depth := event.CallTraceDepth
		eventsByDepth[depth] = append(eventsByDepth[depth], event)
		if depth > maxDepth {
			maxDepth = depth
		}
	}

	fmt.Printf("   📍 Root Events (call chain starters): %d\n", len(rootEvents))
	fmt.Printf("   🌳 Maximum Call Chain Depth: %d\n", maxDepth)
	fmt.Printf("   📊 Events by Depth:\n")

	for depth := 0; depth <= maxDepth; depth++ {
		if eventsAtDepth, exists := eventsByDepth[depth]; exists {
			fmt.Printf("      Depth %d: %d events\n", depth, len(eventsAtDepth))
		}
	}

	fmt.Println()

	// Show sample call chains
	fmt.Println("🔗 SAMPLE CALL CHAINS:")

	sampleCount := 0
	maxSamples := 5

	for _, event := range events {
		if len(event.CallTracePath) > 2 && sampleCount < maxSamples { // Show interesting chains
			fmt.Printf("   📋 Chain %d (depth %d):\n", sampleCount+1, event.CallTraceDepth)
			fmt.Printf("      Path: %s\n", strings.Join(event.CallTracePath, " → "))
			fmt.Printf("      Final Event: %s (ID: %d)\n", event.EventName, event.EmitContext)
			fmt.Printf("      Parent: %s (ID: %d)\n", event.ParentEventName, event.ParentEventID)
			if len(event.ChildEventIDs) > 0 {
				fmt.Printf("      Children: %d events\n", len(event.ChildEventIDs))
			}
			fmt.Println()
			sampleCount++
		}
	}

	if sampleCount == 0 {
		fmt.Println("   No complex call chains found (all events may be root events)")
	}

	// Show most common call patterns
	fmt.Println("📈 MOST COMMON CALL PATTERNS:")
	pathCounts := make(map[string]int)

	for _, event := range events {
		if len(event.CallTracePath) > 1 {
			pathKey := strings.Join(event.CallTracePath, " → ")
			pathCounts[pathKey]++
		}
	}

	// Sort by frequency
	type pathFreq struct {
		path  string
		count int
	}

	var sortedPaths []pathFreq
	for path, count := range pathCounts {
		sortedPaths = append(sortedPaths, pathFreq{path, count})
	}

	// Simple sort by count (descending)
	for i := 0; i < len(sortedPaths)-1; i++ {
		for j := i + 1; j < len(sortedPaths); j++ {
			if sortedPaths[j].count > sortedPaths[i].count {
				sortedPaths[i], sortedPaths[j] = sortedPaths[j], sortedPaths[i]
			}
		}
	}

	// Show top patterns
	showCount := 10
	if len(sortedPaths) < showCount {
		showCount = len(sortedPaths)
	}

	for i := 0; i < showCount; i++ {
		fmt.Printf("   %d. %s (occurred %d times)\n", i+1, sortedPaths[i].path, sortedPaths[i].count)
	}

	if len(sortedPaths) == 0 {
		fmt.Println("   No call patterns found")
	}

	fmt.Println()
}
